use crate::file::FileObject;
use crate::rule::PermissionOp;
use indextree::{Arena, NodeId};
use landlock::{AccessFs, BitFlags};
use std::collections::HashMap;
use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq, Eq)]
struct FsNode {
    fs_object: FileObject,
    add: BitFlags<AccessFs>,
    remove: BitFlags<AccessFs>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Hierarchy {
    tree: Arena<FsNode>,
    root: NodeId,
    index: HashMap<PathBuf, NodeId>,
}

// This is the struct generated by compile. Compile takes the hierarchy once validation has completed
// and extracts the nodes by grabbing their PathBuf and then normalizing the add and remove rules
// into a single BitFlags rules that can be used by landlocks path_beneath
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LandlockReady {
    pub path: PathBuf,
    pub rules: BitFlags<AccessFs>,
}

impl FsNode {
    pub fn new(fs_object: FileObject, add: BitFlags<AccessFs>, remove: BitFlags<AccessFs>) -> Self {
        Self {
            fs_object,
            add,
            remove,
        }
    }

    pub fn new_empty(fs_object: FileObject) -> Self {
        Self {
            fs_object,
            add: BitFlags::empty(),
            remove: BitFlags::empty(),
        }
    }
}

impl Hierarchy {
    pub fn new() -> Self {
        // Create the arena and setup the initial ( root ) node
        let mut tree = Arena::new();
        let root_path: PathBuf = PathBuf::from("/");
        let file_object = FileObject::Directory(root_path.clone());
        let root_id = tree.new_node(FsNode::new_empty(file_object));
        let mut index: HashMap<PathBuf, NodeId> = HashMap::new();
        index.insert(root_path, root_id);

        Self {
            tree,
            root: root_id,
            index,
        }
    }

    pub fn insert_or_update(&mut self, file_object: FileObject, pem_op: PermissionOp) {
        if let Some(node_id) = self.index.get(file_object.path()) {
            let node = self.tree.get_mut(*node_id).unwrap();
            let inner = node.get_mut();
            match pem_op {
                PermissionOp::Add(access) => inner.add |= access,
                PermissionOp::Remove(access) => inner.remove |= access,
            }
        } else {
            let mut ti: Vec<FsNode> = Vec::new();
            let inode = match pem_op {
                PermissionOp::Add(a) => FsNode::new(file_object.clone(), a, BitFlags::empty()),
                PermissionOp::Remove(a) => FsNode::new(file_object.clone(), BitFlags::empty(), a),
            };
            ti.push(inode);

            let mut current_path = file_object.path();
            let mut nearest_node_id = self.root;
            while let Some(parent) = current_path.parent() {
                if let Some(node_id) = self.index.get(parent) {
                    nearest_node_id = *node_id;
                    break;
                } else {
                    let fo = FileObject::Directory(parent.to_path_buf());
                    let fs_node = FsNode::new_empty(fo);
                    ti.push(fs_node);
                }
                current_path = parent;
            }
            ti.iter().rev().for_each(|fs_node| {
                let new_node = self.tree.new_node(fs_node.clone());
                nearest_node_id.append(new_node, &mut self.tree);
                nearest_node_id = new_node;
                self.index
                    .insert(fs_node.fs_object.path().to_path_buf(), nearest_node_id);
            });
        }
    }

    pub fn compile_rules(self) -> Vec<LandlockReady> {
        self.tree
            .iter()
            .filter_map(|node| {
                let node_value = node.get();
                let final_rule = node_value.add & !node_value.remove;

                if final_rule.is_empty() {
                    None
                } else {
                    Some(LandlockReady {
                        path: node_value.fs_object.path().to_path_buf(),
                        rules: final_rule,
                    })
                }
            })
            .collect()
    }
}
